os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - ps: Get-WmiObject -Class win32_operatingSystem 
  - ps: Get-WmiObject -Class Win32_processor
  #- cmd: choco install gpg4win
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Invoke-WebRequest -Uri 'https://files.gpg4win.org/gpg4win-3.1.0.exe' -outfile gpg4win-3.1.0.exe
  - ls
  #- ps: Start-Process -FilePath "$env:appveyor_build_folder/gpg4win.exe" -ArgumentList "/S"
  - gpg4win-3.1.0.exe /S /qn
  - dir "C:/program files (x86)"
  #- ps: Invoke-Command -ScriptBlock {$env:appveyor_build_folder/gnupg.exe /S /v /qn}
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test
